### ISSUE TITLE
Include at:// URIs as alternate links in markup or headers

### ISSUE THREAD

**Issue by tom-sherman** [shinolabs/PinkSea#16]
Hi, cool project!

I've been banging the drum recently for atproto apps to include at:// URIs of the relevant records in the `<link rel="alterate">` tag or `Link` HTTP header.

https://bsky.app/profile/did:plc:2xau7wbgdq4phuou2ypwuen7/post/3l7esaih44s2s

Doing so allows tooling to pick up on the underlying atproto record when presented with a HTTP link to your app. I use this for example in [atproto-browser](https://atproto-browser.vercel.app/) to allow pasting links from Bluesky into the URI bar.

This is already supported by: Bluesky, Frontpage, and WhiteWind as well as a few blogs that run off of atproto records.

Would be great if pinksea supported this! I can see that the frontend is rendered entirely client side which does present some challenges for tooling, ideally this needs to be included in the HTML delivered from the server. Alternatively, it can be included in a [Link HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link)

In HTML an example would look like this:

```html
<head>
  <link rel="alternate" href="at://did:plc:2xau7wbgdq4phuou2ypwuen7/com.shinolabs.pinksea.oekaki/2rat3agmjgvjb" />
</head>
```

And in HTTP headers:

```
Link: <at://did:plc:2xau7wbgdq4phuou2ypwuen7/com.shinolabs.pinksea.oekaki/2rat3agmjgvjb>; rel="alternate"
```

**Comment by tom-sherman** [comment]
Oh wow sorry about the bad example, that's a typo! It should link to the at:// uri

**Comment by purifetchi** [comment]
changes for that are now in this branch https://github.com/shinolabs/PinkSea/tree/oembed :)
